import * as icons from "@heroicons/react/outline";

export enum Icon {
  AcademicCap = "AcademicCap",
  AtSymbol = "AtSymbol",
  BadgeCheck = "BadgeCheck",
  Ban = "Ban",
  Beaker = "Beaker",
  Bell = "Bell",
  BookOpen = "BookOpen",
  Bookmark = "Bookmark",
  BookmarkAlt = "BookmarkAlt",
  Briefcase = "Briefcase",
  Cake = "Cake",
  Calculator = "Calculator",
  Calendar = "Calendar",
  Camera = "Camera",
  Cash = "Cash",
  ChartBar = "ChartBar",
  ChartPie = "ChartPie",
  ChartSquareBar = "ChartSquareBar",
  Chat = "Chat",
  ChatAlt = "ChatAlt",
  ChatAlt2 = "ChatAlt2",
  Check = "Check",
  CheckCircle = "CheckCircle",
  Chip = "Chip",
  Clipboard = "Clipboard",
  ClipboardCheck = "ClipboardCheck",
  ClipboardList = "ClipboardList",
  Clock = "Clock",
  Cloud = "Cloud",
  Code = "Code",
  Cog = "Cog",
  ColorSwatch = "ColorSwatch",
  CreditCard = "CreditCard",
  Cube = "Cube",
  CubeTransparent = "CubeTransparent",
  CurrencyDollar = "CurrencyDollar",
  CursorClick = "CursorClick",
  Database = "Database",
  DesktopComputer = "DesktopComputer",
  DeviceMobile = "DeviceMobile",
  DeviceTablet = "DeviceTablet",
  Document = "Document",
  DocumentDuplicate = "DocumentDuplicate",
  DocumentReport = "DocumentReport",
  DocumentSearch = "DocumentSearch",
  EmojiHappy = "EmojiHappy",
  EmojiSad = "EmojiSad",
  Exclamation = "Exclamation",
  Eye = "Eye",
  Film = "Film",
  FingerPrint = "FingerPrint",
  Fire = "Fire",
  Flag = "Flag",
  FolderOpen = "FolderOpen",
  Gift = "Gift",
  Globe = "Globe",
  Hand = "Hand",
  Hashtag = "Hashtag",
  Heart = "Heart",
  Home = "Home",
  Identification = "Identification",
  Inbox = "Inbox",
  InboxIn = "InboxIn",
  InformationCircle = "InformationCircle",
  Key = "Key",
  Library = "Library",
  LightBulb = "LightBulb",
  LightningBolt = "LightningBolt",
  LocationMarker = "LocationMarker",
  LockClosed = "LockClosed",
  LockOpen = "LockOpen",
  Mail = "Mail",
  MailOpen = "MailOpen",
  Map = "Map",
  Microphone = "Microphone",
  Moon = "Moon",
  Music = "Music",
  Newspaper = "Newspaper",
  OfficeBuilding = "OfficeBuilding",
  PaperAirplane = "PaperAirplane",
  PaperClip = "PaperClip",
  Pause = "Pause",
  Pencil = "Pencil",
  Phone = "Phone",
  Photograph = "Photograph",
  Play = "Play",
  PresentationChartBar = "PresentationChartBar",
  PresentationChartLine = "PresentationChartLine",
  Printer = "Printer",
  Puzzle = "Puzzle",
  QrCode = "QrCode",
  ReceiptRefund = "ReceiptRefund",
  ReceiptTax = "ReceiptTax",
  Rss = "Rss",
  Scale = "Scale",
  Scissors = "Scissors",
  Search = "Search",
  SearchCircle = "SearchCircle",
  Server = "Server",
  Share = "Share",
  ShieldCheck = "ShieldCheck",
  ShieldExclamation = "ShieldExlamation",
  ShoppingBag = "ShoppingBag",
  ShoppingCart = "ShoppingCart",
  Sparkles = "Sparkles",
  Speakerphone = "Speakerphone",
  Star = "Star",
  Sun = "Sun",
  Support = "Support",
  Tag = "Tag",
  Terminal = "Terminal",
  ThumbsDown = "ThumbsDown",
  ThumbsUp = "ThumbsUp",
  Tickets = "Tickets",
  Translate = "Translate",
  Trash = "Trash",
  TrendingDown = "TrendingDown",
  TrendingUp = "TrendingUp",
  Truck = "Truck",
  UserCircle = "UserCircle",
  Variable = "Variable",
  VideoCamera = "VideoCamera",
  VolumeOff = "VolumeOff",
}

export const iconToComponent: Record<
  Icon,
  React.ComponentType<React.ComponentProps<"svg">>
> = {
  [Icon.AcademicCap]: icons.AcademicCapIcon,
  [Icon.AtSymbol]: icons.AtSymbolIcon,
  [Icon.BadgeCheck]: icons.BadgeCheckIcon,
  [Icon.BadgeCheck]: icons.BadgeCheckIcon,
  [Icon.Ban]: icons.BanIcon,
  [Icon.Beaker]: icons.BeakerIcon,
  [Icon.Bell]: icons.BellIcon,
  [Icon.BookOpen]: icons.BookOpenIcon,
  [Icon.BookmarkAlt]: icons.BookmarkAltIcon,
  [Icon.Bookmark]: icons.BookmarkIcon,
  [Icon.Briefcase]: icons.BriefcaseIcon,
  [Icon.Cake]: icons.CakeIcon,
  [Icon.Calculator]: icons.CalculatorIcon,
  [Icon.Calendar]: icons.CalendarIcon,
  [Icon.Camera]: icons.CameraIcon,
  [Icon.Cash]: icons.CashIcon,
  [Icon.ChartBar]: icons.ChartBarIcon,
  [Icon.ChartPie]: icons.ChartPieIcon,
  [Icon.ChartSquareBar]: icons.ChartSquareBarIcon,
  [Icon.ChatAlt2]: icons.ChatAlt2Icon,
  [Icon.ChatAlt]: icons.ChatAltIcon,
  [Icon.Chat]: icons.ChatIcon,
  [Icon.CheckCircle]: icons.CheckCircleIcon,
  [Icon.Check]: icons.CheckIcon,
  [Icon.Chip]: icons.ChipIcon,
  [Icon.ClipboardCheck]: icons.ClipboardCheckIcon,
  [Icon.ClipboardList]: icons.ClipboardListIcon,
  [Icon.Clipboard]: icons.ClipboardIcon,
  [Icon.Clock]: icons.ClockIcon,
  [Icon.Cloud]: icons.CloudIcon,
  [Icon.Code]: icons.CodeIcon,
  [Icon.Cog]: icons.CogIcon,
  [Icon.ColorSwatch]: icons.ColorSwatchIcon,
  [Icon.CreditCard]: icons.CreditCardIcon,
  [Icon.CubeTransparent]: icons.CubeTransparentIcon,
  [Icon.Cube]: icons.CubeIcon,
  [Icon.CurrencyDollar]: icons.CurrencyDollarIcon,
  [Icon.CursorClick]: icons.CursorClickIcon,
  [Icon.Database]: icons.DatabaseIcon,
  [Icon.DesktopComputer]: icons.DesktopComputerIcon,
  [Icon.DeviceMobile]: icons.DeviceMobileIcon,
  [Icon.DeviceTablet]: icons.DeviceTabletIcon,
  [Icon.DocumentDuplicate]: icons.DocumentDuplicateIcon,
  [Icon.DocumentReport]: icons.DocumentReportIcon,
  [Icon.DocumentSearch]: icons.DocumentSearchIcon,
  [Icon.Document]: icons.DocumentIcon,
  [Icon.EmojiHappy]: icons.EmojiHappyIcon,
  [Icon.EmojiSad]: icons.EmojiSadIcon,
  [Icon.Exclamation]: icons.ExclamationIcon,
  [Icon.Eye]: icons.EyeIcon,
  [Icon.Film]: icons.FilmIcon,
  [Icon.FingerPrint]: icons.FingerPrintIcon,
  [Icon.Fire]: icons.FireIcon,
  [Icon.Flag]: icons.FlagIcon,
  [Icon.FolderOpen]: icons.FolderOpenIcon,
  [Icon.Gift]: icons.GiftIcon,
  [Icon.Globe]: icons.GlobeIcon,
  [Icon.Hand]: icons.HandIcon,
  [Icon.Hashtag]: icons.HashtagIcon,
  [Icon.Heart]: icons.HeartIcon,
  [Icon.Home]: icons.HomeIcon,
  [Icon.Identification]: icons.IdentificationIcon,
  [Icon.InboxIn]: icons.InboxInIcon,
  [Icon.Inbox]: icons.InboxIcon,
  [Icon.InformationCircle]: icons.InformationCircleIcon,
  [Icon.Key]: icons.KeyIcon,
  [Icon.Library]: icons.LibraryIcon,
  [Icon.LightBulb]: icons.LightBulbIcon,
  [Icon.LightningBolt]: icons.LightningBoltIcon,
  [Icon.LocationMarker]: icons.LocationMarkerIcon,
  [Icon.LockClosed]: icons.LockClosedIcon,
  [Icon.LockOpen]: icons.LockOpenIcon,
  [Icon.MailOpen]: icons.MailOpenIcon,
  [Icon.Mail]: icons.MailIcon,
  [Icon.Map]: icons.MapIcon,
  [Icon.Microphone]: icons.MicrophoneIcon,
  [Icon.Moon]: icons.MoonIcon,
  [Icon.Music]: icons.MusicNoteIcon,
  [Icon.Newspaper]: icons.NewspaperIcon,
  [Icon.OfficeBuilding]: icons.OfficeBuildingIcon,
  [Icon.PaperAirplane]: icons.PaperAirplaneIcon,
  [Icon.PaperClip]: icons.PaperClipIcon,
  [Icon.Pause]: icons.PauseIcon,
  [Icon.Pencil]: icons.PencilIcon,
  [Icon.Phone]: icons.PhoneIcon,
  [Icon.Photograph]: icons.PhotographIcon,
  [Icon.Play]: icons.PlayIcon,
  [Icon.PresentationChartBar]: icons.PresentationChartBarIcon,
  [Icon.PresentationChartLine]: icons.PresentationChartLineIcon,
  [Icon.Printer]: icons.PrinterIcon,
  [Icon.Puzzle]: icons.PuzzleIcon,
  [Icon.QrCode]: icons.QrcodeIcon,
  [Icon.ReceiptRefund]: icons.ReceiptRefundIcon,
  [Icon.ReceiptTax]: icons.ReceiptTaxIcon,
  [Icon.Rss]: icons.RssIcon,
  [Icon.Scale]: icons.ScaleIcon,
  [Icon.Scissors]: icons.ScissorsIcon,
  [Icon.SearchCircle]: icons.SearchCircleIcon,
  [Icon.Search]: icons.SearchIcon,
  [Icon.Server]: icons.ServerIcon,
  [Icon.Share]: icons.ShareIcon,
  [Icon.ShieldCheck]: icons.ShieldCheckIcon,
  [Icon.ShieldExclamation]: icons.ShieldExclamationIcon,
  [Icon.ShoppingBag]: icons.ShoppingBagIcon,
  [Icon.ShoppingCart]: icons.ShoppingCartIcon,
  [Icon.Sparkles]: icons.SparklesIcon,
  [Icon.Speakerphone]: icons.SpeakerphoneIcon,
  [Icon.Star]: icons.StarIcon,
  [Icon.Sun]: icons.SunIcon,
  [Icon.Support]: icons.SupportIcon,
  [Icon.Tag]: icons.TagIcon,
  [Icon.Terminal]: icons.TerminalIcon,
  [Icon.ThumbsDown]: icons.ThumbDownIcon,
  [Icon.ThumbsUp]: icons.ThumbUpIcon,
  [Icon.Tickets]: icons.TicketIcon,
  [Icon.Translate]: icons.TranslateIcon,
  [Icon.Trash]: icons.TrashIcon,
  [Icon.TrendingDown]: icons.TrendingDownIcon,
  [Icon.TrendingUp]: icons.TrendingUpIcon,
  [Icon.Truck]: icons.TruckIcon,
  [Icon.UserCircle]: icons.UserCircleIcon,
  [Icon.Variable]: icons.VariableIcon,
  [Icon.VideoCamera]: icons.VideoCameraIcon,
  [Icon.VolumeOff]: icons.VolumeOffIcon,
};
